on:
  pull_request:

  push:
    branches:
      - main

  schedule:
    - cron: '0 0 1/1 * *'

name: Build container

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  publish:
    name: Build and publish image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set container tag
        run: |
          echo "CONTAINER_TAG=${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's#^refs/heads/##' | sed -e 's#[^A-Za-z0-9]\+#.#' >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/386
            push: true
            tags: helloseam/tftp-http-proxy:${{ env.CONTAINER_TAG }}
            build-args: |
                CONTAINER_TAG=${{ env.CONTAINER_TAG }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
